// Dummy data — replace with GET /menu and GET /menu/:id once API is ready
export const MENU_ITEMS = [
  {
    id: "1",
    name: "Margherita pizza",
    subtitle: "Wood-fired, classic crust",
    base_price: 249,
    rating: 4.5,
    ratingsCount: 210,
    category: "Pizza",
    icon: "pizza-outline",
    sizes: [
      { label: "Small", price: 249 },
      { label: "Medium", price: 349 },
      { label: "Large", price: 449 },
    ],
    toppings: [
      { id: "cheese", label: "Extra cheese", price: 40 },
      { id: "mushroom", label: "Mushroom", price: 30 },
      { id: "jalapeno", label: "Jalapeno", price: 20 },
    ],
  },
  {
    id: "2",
    name: "Peri-peri pizza",
    subtitle: "Spicy, loaded veggies",
    base_price: 299,
    rating: 4.3,
    ratingsCount: 128,
    category: "Pizza",
    icon: "flame-outline",
    sizes: [
      { label: "Small", price: 299 },
      { label: "Medium", price: 399 },
      { label: "Large", price: 499 },
    ],
    toppings: [
      { id: "cheese", label: "Extra cheese", price: 40 },
      { id: "onion", label: "Onion", price: 15 },
      { id: "jalapeno", label: "Jalapeno", price: 20 },
    ],
  },
  {
    id: "3",
    name: "Garlic bread with cheese",
    subtitle: "Crispy, buttery sides",
    base_price: 149,
    rating: 4.6,
    ratingsCount: 95,
    category: "Sides",
    icon: "restaurant-outline",
    sizes: [
      { label: "Regular", price: 149 },
      { label: "Large", price: 219 },
    ],
    toppings: [{ id: "cheese", label: "Extra cheese", price: 30 }],
  },
  {
    id: "4",
    name: "Chocolate lava cake",
    subtitle: "Warm, gooey center",
    base_price: 179,
    rating: 4.7,
    ratingsCount: 64,
    category: "Desserts",
    icon: "ice-cream-outline",
    sizes: [{ label: "Regular", price: 179 }],
    toppings: [{ id: "icecream", label: "Vanilla ice cream scoop", price: 35 }],
  },
];